image: alpine:latest # Use the latest version of Alpine Linux docker image

pages:
  before_script:
    - apk update && apk add git brotli
    - git clone --depth 5 https://gitlab.com/curben/urlhaus-filter.git urlhaus-filter/

  script:
    - mkdir -p public/
    - cp urlhaus-filter/urlhaus-filter* public/
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\)$' -exec gzip -f -k -9 {} \;
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\)$' -exec brotli -f -k -9 {} \;

  artifacts:
    paths:
      - public/

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "pipeline")'
      when: always
