image: alpine:latest

pages:
  before_script:
    - apk update && apk add git brotli curl
    - git clone --depth 5 https://gitlab.com/curben/urlhaus-filter.git urlhaus-filter/
    - git clone --depth 5 https://gitlab.com/curben/phishing-filter.git phishing-filter/
    - git clone --depth 5 https://gitlab.com/curben/pup-filter.git pup-filter/

    - mkdir -p oisd/
    - curl -L https://abp.oisd.nl/basic/ -o oisd/abp_light.txt
    - curl -L https://abp.oisd.nl/ -o oisd/abp.txt
    - curl -L https://dbl.oisd.nl/basic/ -o oisd/dbl_light.txt
    - curl -L https://dbl.oisd.nl/ -o oisd/dbl.txt
    - curl -L https://dblw.oisd.nl/basic/ -o oisd/dblw_light.txt
    - curl -L https://dblw.oisd.nl/ -o oisd/dblw.txt
    - curl -L https://hosts.oisd.nl/basic/ -o oisd/hosts_light.txt
    - curl -L https://hosts.oisd.nl/ -o oisd/hosts.txt
    - curl -L https://dnsmasq.oisd.nl/basic/ -o oisd/dnsmasq_light.txt
    - curl -L https://dnsmasq.oisd.nl/ -o oisd/dnsmasq.txt
    - curl -L https://rpz.oisd.nl/basic/ -o oisd/rpz_light.txt
    - curl -L https://rpz.oisd.nl/ -o oisd/rpz.txt

  script:
    - mkdir -p public/
    - cp urlhaus-filter/urlhaus-filter* public/
    - cp phishing-filter/dist/phishing-filter* public/
    - cp pup-filter/dist/pup-filter* public/
    - cp oisd/* public/
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\|rules\)$' -exec gzip -f -k -9 {} \;
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\|rules\)$' -exec brotli -f -k -9 {} \;

  artifacts:
    paths:
      - public/

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule")'
      when: always
