image: alpine:latest

build_job:
  stage: build

  before_script:
    - apk update && apk add brotli curl

  script:
    - sh src/script.sh

  artifacts:
    paths:
      - tmp
      - public

pages:
  stage: deploy

  script:
    - echo

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

netlify:
  stage: deploy

  before_script:
      - apk update && apk add curl

  script:
    - curl -X POST -d '{}' https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
