image: alpine:latest # Use the latest version of Alpine Linux docker image

pages:
  before_script:
    - apk update && apk add git
    - git clone --depth 5 https://gitlab.com/curben/urlhaus-filter.git urlhaus-filter/

  script:
    - cd urlhaus-filter/
    - mkdir -p public/
    - cp urlhaus-filter-* public/

  artifacts:
    paths:
      - urlhaus-filter/public/

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "web"'
      when: always
