image: alpine:latest

build_job:
  stage:
    - build

  before_script:
    - apk update && apk add brotli curl

  script:
    - sh src/script.sh

  artifacts:
    paths:
      - tmp
      - public

pages:
  stage:
    - deploy

  script:
    - echo

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
