image: alpine:latest

pages:
  before_script:
    - apk update && apk add git brotli
    - git clone --depth 5 https://gitlab.com/curben/urlhaus-filter.git urlhaus-filter/
    - git clone --depth 5 https://gitlab.com/curben/phishing-filter.git phishing-filter/
    - git clone --depth 5 https://gitlab.com/curben/pup-filter.git pup-filter/

  script:
    - mkdir -p public/
    - cp urlhaus-filter/urlhaus-filter* public/
    - cp phishing-filter/dist/phishing-filter* public/
    - cp pup-filter/dist/pup-filter* public/
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\|rules\)$' -exec gzip -f -k -9 {} \;
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\|rules\)$' -exec brotli -f -k -9 {} \;

  artifacts:
    paths:
      - public/

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "pipeline")'
      when: always
