image: alpine:latest

pages:
  before_script:
    - apk update && apk add git brotli curl
    - git clone --depth 5 https://gitlab.com/curben/urlhaus-filter.git urlhaus-filter/
    - git clone --depth 5 https://gitlab.com/curben/phishing-filter.git phishing-filter/
    - git clone --depth 5 https://gitlab.com/curben/pup-filter.git pup-filter/

    - mkdir -p oisd/
    - curl -L https://abp.oisd.nl/basic/ -o oisd/oisd_abp_light.txt
    - curl -L https://abp.oisd.nl/ -o oisd/oisd_abp.txt
    - curl -L https://dbl.oisd.nl/basic/ -o oisd/oisd_dbl_light.txt
    - curl -L https://dbl.oisd.nl/ -o oisd/oisd_dbl.txt
    - curl -L https://dblw.oisd.nl/basic/ -o oisd/oisd_dblw_light.txt
    - curl -L https://dblw.oisd.nl/ -o oisd/oisd_dblw.txt
    - curl -L https://hosts.oisd.nl/basic/ -o oisd/oisd_hosts_light.txt
    - curl -L https://hosts.oisd.nl/ -o oisd/oisd_hosts.txt
    - curl -L https://dnsmasq.oisd.nl/basic/ -o oisd/oisd_dnsmasq_light.txt
    - curl -L https://dnsmasq.oisd.nl/ -o oisd/oisd_dnsmasq.txt
    - curl -L https://rpz.oisd.nl/basic/ -o oisd/oisd_rpz_light.txt
    - curl -L https://rpz.oisd.nl/ -o oisd/oisd_rpz.txt

    - mkdir -p tracking-filter/
    - git clone --depth 5 https://gitlab.com/curben/tracking-filter.git tracking-filter/

  script:
    - mkdir -p public/
    - cp urlhaus-filter/urlhaus-filter* public/
    - cp phishing-filter/dist/phishing-filter* public/
    - cp pup-filter/dist/pup-filter* public/
    - cp oisd/* public/
    - cp tracking-filter/* public/
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\|rules\)$' -exec gzip -f -k -9 {} \;
    - find public -type f -regex '.*\.\(txt\|conf\|tpl\|rules\)$' -exec brotli -f -k -9 {} \;

  artifacts:
    paths:
      - public/

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule")'
      when: always
